---
version: 2
updates:
  # Enable version updates for ruby
  - package-ecosystem: "bundler"
    # Look for `Gemfile` file in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "elastic/apm-agent-ruby"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "elastic/apm-agent-ruby"
