FROM phusion/passenger-ruby25:latest

ENV HOME /root

RUN rm -f /etc/service/nginx/down
RUN rm /etc/nginx/sites-enabled/default
ADD dockerfiles/webapp.conf /etc/nginx/sites-enabled/webapp.conf
RUN mkdir /home/app/webapp

COPY --chown=app:app . /home/app/webapp

WORKDIR /home/app/webapp

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/sbin/my_init"]
